services:
  - type: web
    name: olympic-medal-metrics
    env: python
    pythonVersion: "3.11"
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    plan: free
